#ifndef XPLAT_CONFIG_H
#define XPLAT_CONFIG_H

#define HAVE_DECL_SIZE_MAX 1
#define HAVE_DECL_SSIZE_MAX 1
#define HAVE_DECL_UINT32_MAX 1
#define HAVE_DECL_INT32_MAX 1
#define HAVE_DECL_INT32_MIN 1
#define HAVE_DECL_UINT64_MAX 1
#define HAVE_DECL_INT64_MAX 1
#define HAVE_DECL_INT64_MIN 1
#define HAVE_DECL_UINTMAX_MAX 1
#define HAVE_DECL_INTMAX_MAX 1
#define HAVE_DECL_INTMAX_MIN 1

#define HAVE_DIRENT_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCHDIR 1
#define HAVE_FCNTL 1
#define HAVE_FCNTL_H 1
#ifndef __WIN32__
  #define HAVE_GRP_H 1
#endif
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H
#define HAVE_UINTMAX_T 1
#define HAVE_UNISTD_H 1
#define HAVE_UNSIGNED_LONG_LONG 1
#define HAVE_WCTYPE_H 1
#define HAVE_WCSCPY 1
#define HAVE_WCSLEN 1

#define MAC_OS_X_VERSION_MIN_REQUIRED 1060
#define MAC_OS_X_VERSION_MAX_ALLOWED 1070

#endif  // XPLAT_CONFIG_H
